In [2]:
#Descriptive Statistics With Python
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/maheshg/Dropbox/Sample Datasets Kaggle/currency_exchange_rate.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3637 entries, 0 to 3636
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3637 non-null   int64
 1   LOCATION    3637 non-null   object
 2   MEASURE     3637 non-null   object
 3   TIME        3637 non-null   int64
 4   Value       3637 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 142.2+ KB

In [4]:
df.head()

   Unnamed: 0 LOCATION MEASURE  TIME     Value
0           0      AUS  NATUSD  1950  0.892857
1           1      AUS  NATUSD  1951  0.892857
2           2      AUS  NATUSD  1952  0.892857
3           3      AUS  NATUSD  1953  0.892857
4           4      AUS  NATUSD  1954  0.892857

In [6]:
#Continuous variable : 
df['Value'].head(10)

0    0.892857
1    0.892857
2    0.892857
3    0.892857
4    0.892857
5    0.892857
6    0.892857
7    0.892857
8    0.892857
9    0.892857
Name: Value, dtype: float64

In [ ]:
#Categorical Variables : 
df[['LOCATION','MEASURE']].head(10)

  LOCATION MEASURE
0      AUS  NATUSD
1      AUS  NATUSD
2      AUS  NATUSD
3      AUS  NATUSD
4      AUS  NATUSD
5      AUS  NATUSD
6      AUS  NATUSD
7      AUS  NATUSD
8      AUS  NATUSD
9      AUS  NATUSD

In [13]:
df['LOCATION'].describe()

count     3637
unique      61
top        AUS
freq        70
Name: LOCATION, dtype: object

In [14]:
df['MEASURE'].describe()

count       3637
unique         1
top       NATUSD
freq        3637
Name: MEASURE, dtype: object

In [15]:
#Distribution Measure : 
df['Value'].kurtosis()

np.float64(144.45402410921474)

In [19]:
import researchpy as rp
rp.summary_cont(df['Value'])

/Users/maheshg/Dropbox/git repos/PythonPractise/PythonPractise-1/study/lib/python3.9/site-packages/researchpy/summary.py:38: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Value' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table.iloc[0,0] = group1.name

  Variable       N      Mean       SD       SE  95% Conf.  Interval
0    Value  3637.0  133.6531  871.313  14.4478   105.3264  161.9797