In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler

In [2]:
data = pd.DataFrame({
    'age': [22,28,35,40,45,50,55,60,65,70],
    'income':[35000,42000,50000,55000,60000,68000,80000,95000,120000,140000]
})

In [3]:
data

   age  income
0   22   35000
1   28   42000
2   35   50000
3   40   55000
4   45   60000
5   50   68000
6   55   80000
7   60   95000
8   65  120000
9   70  140000

In [4]:
data.describe()

             age         income
count  10.000000      10.000000
mean   47.000000   74500.000000
std    15.909466   34416.565779
min    22.000000   35000.000000
25%    36.250000   51250.000000
50%    47.500000   64000.000000
75%    58.750000   91250.000000
max    70.000000  140000.000000

In [5]:
scaler = StandardScaler()
data_standardized = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)

In [6]:
data_standardized

        age    income
0 -1.656392 -1.209785
1 -1.258858 -0.995393
2 -0.795068 -0.750373
3 -0.463790 -0.597236
4 -0.132511 -0.444098
5  0.198767 -0.199079
6  0.530045  0.168451
7  0.861324  0.627863
8  1.192602  1.393550
9  1.523881  2.006100

In [7]:
data_standardized.describe()

                age     income
count  1.000000e+01  10.000000
mean  -6.661338e-17   0.000000
std    1.054093e+00   1.054093
min   -1.656392e+00  -1.209785
25%   -7.122486e-01  -0.712089
50%    3.312784e-02  -0.321589
75%    7.785043e-01   0.513010
max    1.523881e+00   2.006100

In [8]:
data

   age  income
0   22   35000
1   28   42000
2   35   50000
3   40   55000
4   45   60000
5   50   68000
6   55   80000
7   60   95000
8   65  120000
9   70  140000

In [9]:
data.describe()

             age         income
count  10.000000      10.000000
mean   47.000000   74500.000000
std    15.909466   34416.565779
min    22.000000   35000.000000
25%    36.250000   51250.000000
50%    47.500000   64000.000000
75%    58.750000   91250.000000
max    70.000000  140000.000000

In [10]:
scaler = MinMaxScaler()
data_minmax = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)

In [11]:
data_minmax

        age    income
0  0.000000  0.000000
1  0.125000  0.066667
2  0.270833  0.142857
3  0.375000  0.190476
4  0.479167  0.238095
5  0.583333  0.314286
6  0.687500  0.428571
7  0.791667  0.571429
8  0.895833  0.809524
9  1.000000  1.000000

In [12]:
data_minmax.describe()

             age     income
count  10.000000  10.000000
mean    0.520833   0.376190
std     0.331447   0.327777
min     0.000000   0.000000
25%     0.296875   0.154762
50%     0.531250   0.276190
75%     0.765625   0.535714
max     1.000000   1.000000

In [13]:
scaler = RobustScaler()
data_robust = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)

In [14]:
data_robust

        age  income
0 -1.133333  -0.725
1 -0.866667  -0.550
2 -0.555556  -0.350
3 -0.333333  -0.225
4 -0.111111  -0.100
5  0.111111   0.100
6  0.333333   0.400
7  0.555556   0.775
8  0.777778   1.400
9  1.000000   1.900

In [15]:
data_robust.describe()

             age     income
count  10.000000  10.000000
mean   -0.022222   0.262500
std     0.707087   0.860414
min    -1.133333  -0.725000
25%    -0.500000  -0.318750
50%     0.000000   0.000000
75%     0.500000   0.681250
max     1.000000   1.900000

Feature Encoding :

In [16]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

Loading the dataset from seaborn

In [17]:
df = sns.load_dataset('titanic')

In [18]:
df = df[['survived','sex','embarked','class','who']].dropna()

In [19]:
df.head()

   survived     sex embarked  class    who
0         0    male        S  Third    man
1         1  female        C  First  woman
2         1  female        S  Third  woman
3         1  female        S  First  woman
4         0    male        S  Third    man

In [20]:
le = LabelEncoder()

In [21]:
df['sex_le'] = le.fit_transform(df['sex'])
df[['sex','sex_le']].drop_duplicates()

      sex  sex_le
0    male       1
1  female       0

In [22]:
df.head

<bound method NDFrame.head of      survived     sex embarked   class    who  sex_le
0           0    male        S   Third    man       1
1           1  female        C   First  woman       0
2           1  female        S   Third  woman       0
3           1  female        S   First  woman       0
4           0    male        S   Third    man       1
..        ...     ...      ...     ...    ...     ...
886         0    male        S  Second    man       1
887         1  female        S   First  woman       0
888         0  female        S   Third  woman       0
889         1    male        C   First    man       1
890         0    male        Q   Third    man       1

[889 rows x 6 columns]>

Ordinal Encoding

In [23]:
ordinal_order = [['Third','Second','First']]
oe = OrdinalEncoder(categories=ordinal_order)
df['class_ordinal'] = oe.fit_transform(df[['class']])
df[['class','class_ordinal']].drop_duplicates()

    class  class_ordinal
0   Third            0.0
1   First            2.0
9  Second            1.0

In [30]:
edu_df = pd.DataFrame({
    'education':['High School','Bachelors','Masters','Phd']})
    ### Define Manual Mapping
education_map = {
    'High School': 0,
    'Bachelors':1,
    'Masters':2,
    'Phd':3 }

In [31]:
edu_df['education_encoded'] = edu_df['education'].map(education_map)

In [32]:
edu_df

     education  education_encoded
0  High School                  0
1    Bachelors                  1
2      Masters                  2
3          Phd                  3

In [33]:
gen_df = pd.DataFrame ({
    'gender':['Male','Female','Female','Male']
})

In [34]:
gen_df['gender_male'] = (gen_df['gender']== 'Male').astype(int)
gen_df['gender_female'] = (gen_df['gender'] == 'Female').astype(int)

In [35]:
gen_df

   gender  gender_male  gender_female
0    Male            1              0
1  Female            0              1
2  Female            0              1
3    Male            1              0